name: 'Setup Julia environment'
description: 'Setup a Julia environment and add it to the PATH'
author: 'Sascha Mann'
inputs: 
  version:
    description: 'The Julia version to download (if necessary) and use. Example: 1.0.4'
    default: '1'
  include-all-prereleases:
    description: 'Include prereleases when matching the Julia version to available versions.'
    required: false
    default: 'false'
  arch:
    description: 'Architecture of the Julia binaries. Defaults to the architecture of the runner executing the job.'
    required: false
    default: '${{ runner.arch }}'
  show-versioninfo:
    description: 'Display InteractiveUtils.versioninfo() after installing'
    required: false
    default: 'false'
outputs:
  julia-version:
    description: 'The installed Julia version. May vary from the version input if a version range was given as input.'
  julia-bindir:
    description: 'Path to the directory containing the Julia executable. Equivalent to JULIA_BINDIR: https://docs.julialang.org/en/v1/manual/environment-variables/#JULIA_BINDIR'
runs:
  using: 'composite'
  steps:
    - id: juliaup
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "JuliaLang/juliaup"
        latest: true
        fileName: "juliaup-*-x86_64-pc-windows-gnu-portable.tar.gz"
        extract: true
        tarBall: true
        out-file-path: "${{github.workspace}}/.juliaup"
    - id: diag
      shell: pwsh
      run: |
        get-childitem "${{github.workspace}}/.juliaup"
    - id: path
      shell: pwsh
      run: |
        "${{github.workspace}}/.juliaup" | Out-File -FilePath $env:GITHUB_PATH -Append
    - id: julia
      shell: pwsh
      run: |
        juliaup add release
        juliaup default release
    - id: test
      shell: pwsh
      run: |
        julia -v
        juliaup -V
branding:
  icon: 'download'
  color: 'green'
